services:
  # Production Services
  frontend-prod:
    container_name: frontend-prod
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
      args:
        - TURBO_TEAM=${TURBO_TEAM}
        - TURBO_TOKEN=${TURBO_TOKEN}
    restart: always
    ports:
      - "3000:80"
    networks:
      - homelab
    profiles:
      - prod
    environment:
      - VITE_API_URL=http://api-prod:3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-prod.rule=Host(`dnd.your-domain.com`)"
      - "traefik.http.routers.frontend-prod.entrypoints=websecure"
      - "traefik.http.routers.frontend-prod.tls.certresolver=myresolver"
      - "traefik.http.services.frontend-prod.loadbalancer.server.port=80"

  api-prod:
    container_name: api-prod
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
      args:
        - TURBO_TEAM=${TURBO_TEAM}
        - TURBO_TOKEN=${TURBO_TOKEN}
    restart: always
    ports:
      - "3001:3000"
    networks:
      - homelab
    profiles:
      - prod
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-prod.rule=Host(`api.dnd.your-domain.com`)"
      - "traefik.http.routers.api-prod.entrypoints=websecure"
      - "traefik.http.routers.api-prod.tls.certresolver=myresolver"
      - "traefik.http.services.api-prod.loadbalancer.server.port=3000"

  # Development Services
  frontend-dev:
    container_name: frontend-dev
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile.dev
    volumes:
      - ./apps/frontend:/app/apps/frontend
      - /app/apps/frontend/node_modules
    command: pnpm --filter frontend exec vite
    ports:
      - "3000:3000"
    networks:
      - homelab
    profiles:
      - dev
    environment:
      - VITE_API_URL=http://api-dev:3001
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-dev.rule=Host(`dnd.weeboo.xyz`)"
      - "traefik.http.routers.frontend-dev.entrypoints=websecure"
      - "traefik.http.routers.frontend-dev.tls.certresolver=myresolver"
      - "traefik.http.services.frontend-dev.loadbalancer.server.port=3000"

  api-dev:
    container_name: api-dev
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.dev
    volumes:
      - ./apps/api:/app/apps/api
      - /app/apps/api/node_modules
    command: pnpm --filter api exec nest -- start --watch
    ports:
      - "3001:3001"
    networks:
      - homelab
    profiles:
      - dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-dev.rule=Host(`api.weeboo.xyz`)"
      - "traefik.http.routers.api-dev.entrypoints=websecure"
      - "traefik.http.routers.api-dev.tls.certresolver=myresolver"
      - "traefik.http.services.api-dev.loadbalancer.server.port=3001"

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  homelab:
    external: true
