FROM node:20-alpine
ENV NODE_ENV=development
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH:/app/node_modules/.bin"
RUN corepack enable

WORKDIR /app

COPY .npmrc .
COPY . .

RUN pnpm install --prod=false

# This command is overridden by docker-compose.override.yml
CMD pnpm --filter frontend run dev 